# Generated by Django 5.2.17 on 2026-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0002_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_order_product"
            ),
        ),
    ]
