# Generated by Django 5.2.17 on 2026-08-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
