# Generated by Django 5.2.17 on 2026-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
