# Generated by Django 5.2.17 on 2026-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="client_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
