# Generated by Django 5.2.17 on 2026-08-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_paymentattempt_client_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="qr_url",
            field=models.URLField(blank=True),
        ),
    ]
