# Generated by Django 5.2.17 on 2026-08-20 02:17

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.fields


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_paymentattempt_qr_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="paymongo_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", apps.fields.MoneyField()),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("failure_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
