# Generated by Django 5.2.17 on 2026-08-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentattempt_paymongo_payment_id_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='redirect_url',
            field=models.URLField(blank=True),
        ),
    ]
