# Generated by Django 5.2.17 on 2026-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_paymentattempt_redirect_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentattempt",
            name="qr_url",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="redirect_url",
            field=models.TextField(blank=True),
        ),
    ]
