# Generated by Django 5.2.17 on 2026-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentattempt_qr_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
