# Generated by Django 5.2.17 on 2026-08-24 16:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("digital_download", "Digital Download"),
                    ("course", "Course or Tutorial"),
                    ("ebook", "E-book"),
                    ("membership", "Membership"),
                    ("bundle", "Bundle"),
                ],
                default="digital_download",
                help_text="What the buyer receives. Delivery is file/link based for all types: downloads for files, links for course portals, etc.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Buyer-facing label, e.g. 'Starter Kit (ZIP)'", max_length=200
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("download", "Download"), ("stream", "Stream / External Link")],
                        default="download",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload the deliverable. Required when kind is Download.",
                        upload_to=apps.catalog.models.product_file_upload_path,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Destination link for Stream items (course portal, video page…).",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Bytes; auto-filled on upload.", null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
