# Generated by Django 5.2.17 on 2026-08-25 16:56

from django.db import migrations

import apps.fields


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_category_icon_code_xml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="external_url",
            field=apps.fields.HTTPSURLField(
                blank=True,
                help_text="Destination link for Stream items (course portal, video page…).",
            ),
        ),
    ]
