# Generated by Django 5.2.17 on 2026-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_productfile_external_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for the product card. Falls back to category icon if not provided.",
                null=True,
                upload_to="product_covers/",
            ),
        ),
    ]
