# Generated by Django 5.2.17 on 2026-08-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_membership_duration_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('brand_name', models.CharField(help_text='Store or brand name the creator sells under.', max_length=150)),
                ('portfolio_url', models.URLField(blank=True, help_text='Website, GitHub, Behance, or any work showcase.')),
                ('social_url', models.URLField(blank=True, help_text='Instagram, TikTok, Facebook page, or similar.')),
                ('message', models.TextField(help_text='What the creator wants to sell and why it fits Raqnith.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category the applicant plans to sell in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_applications', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
