# Generated by Django 5.2.17 on 2026-08-25 16:56

import apps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='portfolio_url',
            field=apps.fields.HTTPSURLField(blank=True, help_text='Website, GitHub, Behance, or any work showcase.'),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='social_url',
            field=apps.fields.HTTPSURLField(blank=True, help_text='Instagram, TikTok, Facebook page, or similar.'),
        ),
    ]
